### ISSUE TITLE
benchmarksgame-mirror out of date

### ISSUE THREAD

**Issue by dc25** [Byron/benchmarksgame-cvs-mirror#1]
Most recent update was in December.  Per suggestion on the readme, I'm filing an issue.

**Comment by Byron** [comment]
Thanks for letting me know!

Here is the cause of the issue:
```
[...]
Already up-to-date.
Already on 'master'
Already up-to-date.

remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: e6d8b254545aaf3b7c8f1ee61be2e59d
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File website/websites/u64q/code/fasta.4.php.log is 124.43 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/Byron/benchmarksgame-cvs-mirror
 ! [remote rejected] master -> master (pre-receive hook declined)
 ! [remote rejected] origin -> origin (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/Byron/benchmarksgame-cvs-mirror'
```

As the machine running this will not be around anymore by the end of the year, I am working on dockerizing the process, making it easier for others to run it and even submit PRs with updates (if necessary).

Let's see if it's possible to skip the website.

**Comment by Byron** [comment]
The repository was updated.
Additionally, quite a few things changed:

* use docker to document actual system requirements to run `git cvsimport`
* add `Makefile` to make it easy to update local clones yourself
* remove cron-job on remote machine.
   This wasn't a technical requirement as I could have restored this functionality, but knowing that the machine will be gone soon, I thought it was not worth the time.

For now, this repository is not automatically updated anymore, unless I configure my mac to run update from time to time.
