### ISSUE TITLE
make contributions easier ;  make forking easier

### ISSUE THREAD

**Issue by igouy** [Byron/benchmarksgame-cvs-mirror#2]
Thanks for the interest.

> … using technology that makes contributions harder than they have to be. Even though I don't think this repository will help easing contributions…

So if this partial mirror repo won't make it easier to contribute programs and won't make forking the benchmarks game project easier … What would?

Currently your repo isn't sufficient for someone to know whether a program in the repo gives a correct result. 

Currently your repo isn't sufficient for someone to know whether a program in the repo would be considered valid.

> … at least it helps to get a good look at the latest code.

3-clicks from the benchmarks game homepage to the program source-code

**Comment by Byron** [comment]
Thanks for the feedback.

From what I read, I can't shake the feeling that you took some personal offense in the way the Readme is written, and if so, please accept my apologies.

As my goals for this project are satisfied and the auto-update seems to be working, I won't spend any more time on it. However, if you have ideas on how to make it better/more useful, please feel free to create a PR.

**Comment by igouy** [comment]
> some personal offense

Nope. Just peculiar to say there's a problem and then say but this doesn't help.

Perhaps with more understanding, you may have thought to copy the expected output files and task descriptions into the bench directory. At-least you prompted me to do that, so thanks.

**Comment by Byron** [comment]
It appears the auto-updated stopped working in May, and I am closing this issue as it's likely I will soon archive the repository.
