### ISSUE TITLE
mirror the archive

### ISSUE THREAD

**Issue by igouy** [Byron/benchmarksgame-cvs-mirror#3]
> All other git-mirrors I found were out-of-date

For completeness, you could mirror the programs for a much wider range of languages / language implementations that were contributed pre-2008.

https://alioth.debian.org/scm/viewvc.php/shootout/bench/?root=shootout

**Comment by Byron** [comment]
Good idea - I am looking into this right now.

**Comment by igouy** [comment]
Cool. Be aware that both the old shootout and current benchmarks game projects, grievously misuse CVS.

Whole file addition & whole file removal & whole file replacement are used as processing / update triggers. So although there may be 3 "versions" of spectralnorm.rust-2.rust, they could be completely different programs contributed by different authors. 

afaict the significance of the arbitrary naming and versioning for your mirror repos is the need to extract / mirror files that have been deleted / removed from CVS.

For example:

https://alioth.debian.org/scm/viewvc.php/benchmarksgame/bench/spectralnorm/?root=benchmarksgame&hideattic=0

:note the dead ats, cint, clean, etc etc programs.

**Comment by Byron** [comment]
I have created the archive, it looks like the cvs download is complete now. https://github.com/Byron/benchmarksgame-cvs-mirror-pre-2008
